#!/usr/bin/env python3.10
from argument_parser import parse_arguments
from command_line import get_arguments
from creator import Creator


def main():
    args = get_arguments()
    app_settings = parse_arguments(args)
    Creator(app_settings).create()


if __name__ == "__main__":
    main()
