#!/usr/bin/env python3.10
import component

from command_line import get_arguments
from argument_parser import parse_arguments


def main():
    args = get_arguments()
    app_settings = parse_arguments(args)
    component.create(app_settings)


if __name__ == "__main__":
    main()
